name: 'Match against glob'
description: 'Matches filenames against glob patterns. Uses minimatch'
inputs:
  filenames:
    description: 'List one or many strings to test'
    required: true
  patterns:
    description: 'List one or many glob patterns to test against'
    required: true
outputs:
  match: 
    description: 'True if at least one filename matches against at least one glob. False if no matches were found'
  files: 
    description: 'Lists all files matching the patterns'
runs:
  using: 'node12'
  main: 'src/index.js'

